In [36]:
import numpy as np

X = np.array([[14, 641], [62, 594]])
n = X.sum()

print(X)

X_idot: np.ndarray = X.sum(axis=1)[:, None]
X_jdot: np.ndarray = X.sum(axis=0)[:, None]

E = (X_idot @ X_jdot.T) / n

T = 2*(X * np.log(X / E)).sum()

[[ 14 641]
 [ 62 594]]
[[655]
 [656]]
[[  76]
 [1235]]
[[ 37.97101449 617.02898551]
 [ 38.02898551 617.97101449]]
34.5335058946819


In [37]:
X_jdot.T

array([[  76, 1235]])

In [38]:
X/E

array([[0.36870229, 1.03884909],
       [1.63033537, 0.96121013]])

In [39]:
print(X_idot)
print(X_jdot)

[[655]
 [656]]
[[  76]
 [1235]]


In [40]:
E*n

array([[ 49780., 808925.],
       [ 49856., 810160.]])

In [41]:
# %reset -f