In [40]:
import numpy as np
from numpy.linalg import eig

P = np.array([
    [0.4,  0.5, 0.1],
    [0.05, 0.7, 0.25],
    [0.05, 0.5, 0.45]
])
eigenvalues, eigenvectors = eig(P.T)
print(eigenvalues)
print(eigenvectors)

pi_dist = eigenvectors[:, 0]
print(pi_dist)

[1.   0.35 0.2 ]
[[ 1.10410489e-01  7.07106781e-01  8.17634509e-17]
 [ 8.97085227e-01 -3.24568369e-16 -7.07106781e-01]
 [ 4.27840647e-01 -7.07106781e-01  7.07106781e-01]]
[0.11041049 0.89708523 0.42784065]


In [41]:
pi_dist @ P

array([0.11041049, 0.89708523, 0.42784065])

In [42]:
%reset -f